# Generated by KMK Configurator
import board
from kmk.kmk_keyboard import KMKKeyboard
from kmk.keys import KC
from kmk.scanners import DiodeOrientation
from kmk.modules.layers import Layers
from kmk.modules.macros import Macros, Tap, Press, Release, Delay

keyboard = KMKKeyboard()

# --- Modules ---
keyboard.modules.append(Layers())
keyboard.modules.append(Macros())


# --- Hardware Settings ---
keyboard.diode_orientation = DiodeOrientation.COL2ROW
keyboard.col_pins = (board.GP0, board.GP1,)
keyboard.row_pins = (board.GP2, board.GP3,)

# --- Macro Definitions ---
ABCD = KC.MACRO(Delay(1), Delay(1), Delay(1))
CTRLC = KC.MACRO(Press(KC.LCTL), Press(KC.C), Release(KC.LCTL), Release(KC.C))

# --- Keymap ---
keyboard.keymap = [
    # Layer 0
    [
        KC.A, KC.B,
        KC.TG(1), CTRLC,
    ],
    # Layer 1
    [
        KC.C, KC.D,
        KC.TG(1), ABCD,
    ],
]


if __name__ == '__main__':
    keyboard.go()